version: '2'

networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-mediawiki-web:
    image: mediawiki
    container_name:  §§INSTANCE-mediawiki-web
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - §§INSTANCE-mediawiki-db:mediawiki-db
    ports:
      - "§§PORT1:80"
    depends_on:
      - §§INSTANCE-mediawiki-db
      - §§INSTANCE-mediawiki-data
    volumes_from: 
      - §§INSTANCE-mediawiki-data

  §§INSTANCE-mediawiki-db:
    image: mariadb
    container_name: §§INSTANCE-mediawiki-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    user: root
    environment:
      - MYSQL_DATABASE: mediawiki
      - MYSQL_USER: wikiuser
      - MYSQL_PASSWORD: §§MYSQLPW
      - MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes_from: 
      - §§INSTANCE-mediawiki-data
    depends_on:
      - §§INSTANCE-mediawiki-data

  §§INSTANCE-mediawiki-data:
    image: busybox
    container_name: §§INSTANCE-mediawiki-data
    volumes:
      - ./data/images:/var/www/html/images
      - ./data/mysql:/var/lib/mysql
      - ./config/LocalSettings.php:/var/www/html/LocalSettings.php
      - ./config/MediaWikiLogo.png:/var/www/html/MediaWikiLogo.png
      - ./config/extensions:/var/www/html/extensions